### ISSUE TITLE
`encode` explodes if state does not exist

### ISSUE THREAD

**Issue by jmeas** [leeluolee/stateman#10]
`stateman.encode('state-that-doesnt-exist')`

> Uncaught TypeError: Cannot read property 'encode' of undefined

This is a matter of preference, but I would probably return `undefined`.

===

I'll PR this if you want to change it @leeluolee.

**Comment by leeluolee** [comment]
I've fixed this bug.  but not publish yet  ,   :)

**Comment by jmeas** [comment]
:+1:
