### ISSUE TITLE
Redundant "notfound" functionality

### ISSUE THREAD

**Issue by jmeas** [leeluolee/stateman#11]
There are two ways to add notfound functionality, a `$notfound` state, and the `notfound` event. Not too big a deal, I guess, but I don't think both are necessary. Fwiw `$notfound` is not documented, and can only be found in the src and examples.

**Comment by leeluolee** [comment]
Beacuse I also consider that they are redundant , so I didn't documented `$notfound`.   but A old project have used it ,  I will remove it in future . 

I'm very glad  that you have been diving into stateman's sourcecode
