### ISSUE TITLE
Histery vs. History

### ISSUE THREAD

**Issue by jmeas** [leeluolee/stateman#12]
I don't think that this library needs to call it "Histery." The only conflict would be `window.history`, but the lib is not attaching an instance of `Histery` to the global scope.

I'd prefer it to be called History, 'cause it's more in line with what people would expect. Backbone, for instance, calls it Backbone.History.

If you are :+1: @leeluolee I will make a PR.

**Comment by leeluolee** [comment]
feel free to make a PR. :+1:

**Comment by leeluolee** [comment]
#27
