### ISSUE TITLE
src/histery.js 为啥不是 src/history.js ?

### ISSUE THREAD

**Issue by tcdona** [leeluolee/stateman#18]
挺喜欢这个库的，还在看，希望足够简洁。

**Comment by leeluolee** [comment]
https://github.com/leeluolee/stateman/issues/12 也提到了。 当初只是怕和浏览器的history 命名冲突了 ， 因为也只是个内部模块

**Comment by leeluolee** [comment]
已经被一个热心网友更新为history

**Comment by leeluolee** [comment]
#27
