### ISSUE TITLE
Cleanup and work coordination

### ISSUE THREAD

**Issue by hippich** [leeluolee/stateman#27]
I found quite a few issues with code when was closely debugging some issues. I was thinking about cleaning up code and fixing these issues, and adding ESLint config to prevent these from cropping-in in future. But this will make any merges almost impossible.. Do you think you get to the point where you are "done" with changes for enough time for me to make few passes on improving quality of the code? So we do not work on the code base at the same time.

**Comment by leeluolee** [comment]
I'm very glad to see that stateman can garnered contributions from other developers.

You can just do that.  Make sure the new branch is created  from branch <develop>.   

This project was refactor from several SPA that we created.  Maybe something are not well designed for all  usecases. 

But, If you found that the contribution will change the process (navigation process), please discussed in advance for finding potential  risk   . any other code  clean or api changing  won't be a big issue.

**Comment by leeluolee** [comment]
There are two works is still  in development, all of them are simple to implement. 

1.  priority config  #22 

 If we make the newer state have the higher priority than older one to hit the url matching , we can resolve the issue.  


2. canUpdate #26


Yes, both of them are contributed by you, thanks.
