### ISSUE TITLE
state.url中有"."时无法获得状态, 不能进入enter方法

### ISSUE THREAD

**Issue by Sartner** [leeluolee/stateman#29]
url: #/redis/:name

当name为redis_192.168.1.1时无法获得状态
修改成redis_192_168_1_1正常

**Comment by leeluolee** [comment]
默认pattern是[-\$\w]+ .不匹配    ， 你可以这样设置   '/:name([.\\w+]+)'   . 其中双斜杠是为了避免字符串里的转移

[参考文档: 路由参数](http://leeluolee.github.io/stateman/?doc=API&lang=zh#stateman-文档-理解routing-routing-参数)

**Comment by leeluolee** [comment]
一直没反馈， 我就关了
