### ISSUE TITLE
是用一个循环不停检测URL变化吗？

### ISSUE THREAD

**Issue by tuoxiansp** [leeluolee/stateman#3]
代码不大看得懂。。发现使用浏览器的回退也会抛出'begin'事件。。这样的话，一个复杂的单页应用想要回退怎么办，我想要知道这次begin事件是回退来的，而不是主动nav过来的，区别是：浏览器原生的回退是返回到上一个页面，并保持离开之前的状态，而现在好像不容易做到。

**Comment by leeluolee** [comment]
@tuoxiansp 不是。 原理如下: 
1. 高版本浏览器(支持history pushState相关的, 如chrome)并且你开启了html5支持: 监听 popstate事件 
2. 较低版本(支持onhashchange事件, 如IE8)： 是检测 hashchange事件
3. 更低版本的2B浏览器(IE6/7): 如你所说是轮训. 是检测 hash地址

回退了之后会导致路径变化，自然而然会触发stateman的begin事件. 对于你常规的非单页应用，后台路由会处理回退回来还是定位的吗？ 到客户端也是自然。  路由驱动的单页开发，有一个简单的准则。

模块逻辑的开始，始终从url状态驱动，保证无论从nav、回退、前进 达到的效果都是一致的。  保证单向性

**Comment by leeluolee** [comment]
你每次通过stateman.nav  或go 都会在历史上留下痕迹 （假如你没有传入replace参数）。  可以用来后退和前进。

**Comment by tuoxiansp** [comment]
哈哈，明白啦，谢谢！解释的真详细！
