### ISSUE TITLE
怎样可以连续点击url

### ISSUE THREAD

**Issue by chenyeyuze** [leeluolee/stateman#33]
你好，我尝试在项目中使用你的stateman，可是发现路由绑定的函数不允许连续触发两次的，就是不能连续点击同一个url，你网上的demo也是这样。。http://leeluolee.github.io/stateman/example/api.html#/app，是不是要配置什么参数才能支持连续点击，我在文档上找不到具体的。。

**Comment by leeluolee** [comment]
不是不允许， 是第二次点了没意义， 因为是同一个路径
