### ISSUE TITLE
stateman.nav(url, option, cb)这个函数的option参数好像没有用

### ISSUE THREAD

**Issue by tuoxiansp** [leeluolee/stateman#4]
RT，看了代码，也用API.html测试了一下，这个参数没有文档里讲的
{
      Example
      stateman.nav("/app/contact/1?name=leeluolee", {data: 1});
      最终传入到enter, leave与update的option参数会是{param: {id: "1", name:"leeluolee"}, data: 1}.
}
这个作用。

**Comment by leeluolee** [comment]
试了下确实，3Q。  其实go和nav 走的都是内部的_go函数的流程， 不过看了下代码 nav走完后options丢失了， 这个testcase也缺失。 我补一下，等会发布。

还有你睡挺晚的。

**Comment by leeluolee** [comment]
只有来自 url的 param 被捕捉到了

**Comment by tuoxiansp** [comment]
我擅长夜里工作 :-D

**Comment by leeluolee** [comment]
Fix in [`v0.1.8`](https://github.com/leeluolee/stateman/releases/tag/v0.1.8)
