### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by jmeas** [leeluolee/stateman#7]
I think that the API around async methods is limited by the fact that this library assumes that Promises don't exist.

@leeluolee, I understand that you have two priorities:

1. Support old IEs
2. Don't include a Promise library

These are priorities that I, too, share. But I **still** build my libraries assuming Promises, because they are a familiar tool for devs, and they make for a much nicer API.

What I do is require that the developer set `Library.Promise` before they can use the library, if they're in a legacy environment. Other popular libraries have adopted this pattern, too. Here's [a good example.](https://github.com/orbitjs/orbit.js/blob/master/lib/orbit.js#L27-L29)

I would wager that a surprising number of developers use a Promise implementation in their source, so it's not creating too much extra effort for them, I think.

This would allow you to get rid of the `var done = this.async()` pattern, and instead switch to: `return myPromise;`, which I find way nicer!

===

Little summary of pros/cons...

Pros:

- Devs get to continue using Promises, which they're likely familiar with.
- Devs don't need to learn this less-familiar, more-verbose pattern

Cons:

- Slightly more work setting up the library if you need to support older IEs

**Comment by leeluolee** [comment]
Very convincing suggestion.   	I'll think it over

**Comment by leeluolee** [comment]
included partial support in v0.2.0
